version: '2'
services:
  app:
    restart: always
    build: ./app
    expose:
      - "80"
    links:
      - postgres:postgres
    volumes:
      - ./app:/usr/src/app/
    env_file: .env
    environment:
      - FLASK_DEBUG=1
      - DEBUG=1
    command: "/usr/local/bin/gunicorn --reload -w 1 -b :80 app:app"

  nginx:
    build: ./nginx/
    ports:
      - "8080:8080"
    volumes:
      - /www/static
    volumes_from:
      - app
    links:
      - app:app

  data:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
      - ./dbdata:/var/lib/postgresql/dbdata
    command: "true"

  postgres:
    image: postgres:latest
    volumes_from:
      - data
    ports:
      - "5432:5432"
